### ISSUE TITLE
Figure code include in the paper

### ISSUE THREAD

**Issue by YuWang07** [BIMIB-DISCo/SARS-CoV-2-IHMV#1]
Dear Daniele,

Thanks for the beautiful work, I learn a lot.
I was wondering is the figure's in the paper also uploaded in to this github page?

Best,
Yu.

**Comment by danro9685** [comment]
Dear @YuWang07,

Thank you for your interest in our work. I have included @DavideMaspero who can help you with your issue.

All the best,
Daniele

**Comment by DavideMaspero** [comment]
Dear Yu,

I uploaded a new directory called figures, where you can find the 'generate_plots.R' script. Simply move to that directory with R/Rstudio and run/source the script. 

Required dependencies are listed in the first lines of the code.
Please, let me know if you encounter any problems.

Best,
Davide

**Comment by danro9685** [comment]
Thanks @DavideMaspero.
Closing this as it is fixed, let us know @YuWang07 if you have any other question.

All the best,
Daniele
